import React, { useState } from "react";
import { makeStyles } from "@material-ui/core/styles";
import Typography from "@material-ui/core/Typography";

export default function Test1() {
  const [words, setWords] = useState([
    "cider",
    "cast",
    "stripe",
    "insert",
    "defend",
    "bough",
    "blind",
    "coarse",
    "court",
    "settle",
    "fudge",
    "chord",
    "govern",
    "pearl",
    "lodge",
    "greet",
    "solar",
    "perfect",
    "bridle",
    "oaken",
    "fault",
    "spoon",
    "special",
    "recess",
    "crown",
    "leap",
    "piece",
    "consist",
    "soapy",
    "quest",
    "count",
    "rinse",
    "mostly",
    "able",
    "glimpse",
    "shore",
    "drawn",
    "shrink",
    "pledge",
    "every",
    "easel",
    "fleet",
    "pencil",
    "refuse",
    "break",
    "define",
    "sense",
    "hinder",
    "better",
    "where",
    "entire",
    "uncle",
    "solace",
    "patrol",
    "thorn",
    "ghost",
    "white",
    "keeper",
    "judge",
    "pause",
    "knife",
    "coach",
    "night",
    "defect",
    "hence",
    "hedge",
    "south",
    "clock",
    "trust",
    "short",
    "petal",
    "period",
    "picnic",
    "other",
    "person",
    "scope",
    "miller",
    "smart",
    "straw",
    "warm",
    "ripen",
    "slogan",
    "finger",
    "noisy",
    "juice",
    "under",
    "height",
    "useful",
    "defer",
    "enter",
    "heard",
    "event",
    "slowly",
    "field",
    "ordeal",
    "quite",
    "bond",
    "meant",
    "mend",
    "nurse",
    "jump",
    "west",
    "quick",
    "skill",
    "cool",
  ]);
  return (
    <>
      <h2>Finding A’s test :</h2>
      <h3>
        Instruction:{" "}
        <h4>
          Please complete the Finding a’s test. Your job is to select all the
          words that contain the letter a. You have 3 minutes to complete this.
          Good luck!
        </h4>{" "}
        Time Limit: 3 minutes
      </h3>
    </>
  );
}
